import { Component } from '@angular/core';
//import {OnBoardingServiceService} from './on-boarding-service.service'
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'NCS Talent Management System';
  constructor(){};
  //array of months.
  columnName= ["Group","JD Role","Location","Niche / Commodity","Key Posn","Customer Role Mapping","Role /Technology Mapping","Technology Group","Role Group","Relevant Exp",	"Exp on Date of Onboarding","NCS Contact","Raised On (by Client)",
  "Need By","VAC Onboarding Date","Onboarding Month","Profile Shared Date","Interview Date"];
  //,"Client Confirmation Date","VAC Offboarding Date","Infosys Unit Owner","PSO Status","Onboarding Status","Merged Status",	
  //"Infosys Emp #","Candidate ID",	"Name",	"Job Role","Contract Role","Infosys Designation","PU",	"DU","Project Code","NCS ID","NCS Email","Interview Status","Lateral","Infys DOJ","Remarks"
  demandtrackernew = [{
    "GroupInfo": "Chief Architect Office",
    "JD_Role": "DevOps Specialists",
    "Location": "Offshore",
    "Niche_Commodity": "Niche",
    "Key_Posn": "Y",
    "Customer_Role_Mapping": "DevOps Specialists",
    "Role_Technology_Mapping": "DevOps Specialists",
    "Technology_Group": "DevOps",
    "Role_Group": "Others",
    "Relevant_Exp": "2-5",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Srirengan Kumar ",
    "Raised_On_by_Client": "4-Oct-17",
    "Need_By": "1-Dec-17",
    "VAC_onboarding_Date": "31-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "3-Jan-18",
    "Interview_Date": "15-Jan-18",
    "Client_confirmation_Date": "15-Jan-18",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "781299",
    "Candidate_ID": "",
    "Name": "Sinchan Doshi",
    "Job_Role": "DevOps Specialists",
    "Contract_Role": "DevOps Specialists",
    "Infosys_Designation": "Associate Consultant",
    "PU": "ECSADMC",
    "DU": "ECSADMC-DOA",
    "Project_Code": "NCO101PD",
    "NCS_ID": "ncssinchandoshi",
    "NCS_Email": "sinchan.doshi@ncs.com.sg",
    "Interview_Status": "Closed - Interview done",
    "Lateral": "NonSingtelSlot",
    "Infys_DOJ": "26-Dec-17",
    "Remarks": ""
  },
  {
    "GroupInfo": "Chief Architect Office",
    "JD_Role": "DevOps Specialists",
    "Location": "Offshore",
    "Niche_Commodity": "Niche",
    "Key_Posn": "",
    "Customer_Role_Mapping": "DevOps Specialists",
    "Role_Technology_Mapping": "DevOps Specialists",
    "Technology_Group": "DevOps",
    "Role_Group": "Others",
    "Relevant_Exp": "2-5",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Srirengan Kumar ",
    "Raised_On_by_Client": "4-Oct-17",
    "Need_By": "1-Dec-17",
    "VAC_onboarding_Date": "1-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "15-Dec-17",
    "Interview_Date": "",
    "Client_confirmation_Date": "1-Dec-17",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "777155",
    "Candidate_ID": "",
    "Name": "Vipin kumar Sharma",
    "Job_Role": "Junior DevOps Specialists",
    "Contract_Role": "Business Analyst",
    "Infosys_Designation": "Associate Consultant",
    "PU": "ECSADMC",
    "DU": "ECSADMC-DOA",
    "Project_Code": "NCO101PD",
    "NCS_ID": "ncsvipinsharma",
    "NCS_Email": "vipin.sharma@ncs.com.sg",
    "Interview_Status": "Closed - Interview done",
    "Lateral": "NonSingtelSlot",
    "Infys_DOJ": "27-Nov-17",
    "Remarks": ""
  },
  {
    "GroupInfo": "Chief Architect Office",
    "JD_Role": "Java Architect",
    "Location": "Offshore",
    "Niche_Commodity": "Niche",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Architect",
    "Role_Technology_Mapping": "Architect Java",
    "Technology_Group": "Java/J2EE",
    "Role_Group": "Architect",
    "Relevant_Exp": ">6",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Srirengan Kumar ",
    "Raised_On_by_Client": "4-Oct-17",
    "Need_By": "1-Dec-17",
    "VAC_onboarding_Date": "30-Mar-18",
    "Onboarding_Month": "Mar",
    "Profile_Shared_Date": "27-Mar-18",
    "Interview_Date": "",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Mapped",
    "Onboarding_Status": "Ready for Onboarding",
    "Merged_Status": "Ready for Onboarding-Mapped",
    "Infosy_Emp_Id": "776172",
    "Candidate_ID": "",
    "Name": "Sagar Sheshrao Deulkar",
    "Job_Role": "Lead Architect",
    "Contract_Role": "Lead Architect",
    "Infosys_Designation": "Senior Technology Architect ",
    "PU": "ECSADMCATS",
    "DU": "ECSADM-CATS",
    "Project_Code": "",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "NonLateral",
    "Infys_DOJ": "",
    "Remarks": ""
  },
  {
    "GroupInfo": "Chief Architect Office",
    "JD_Role": "Java Architect",
    "Location": "Offshore",
    "Niche_Commodity": "Niche",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Architect",
    "Role_Technology_Mapping": "Architect Java",
    "Technology_Group": "Java/J2EE",
    "Role_Group": "Architect",
    "Relevant_Exp": ">6",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Srirengan Kumar ",
    "Raised_On_by_Client": "4-Oct-17",
    "Need_By": "1-Dec-17",
    "VAC_onboarding_Date": "",
    "Onboarding_Month": "",
    "Profile_Shared_Date": "",
    "Interview_Date": "",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "1",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Open",
    "Onboarding_Status": "Open",
    "Merged_Status": "Open-Open",
    "Infosy_Emp_Id": "",
    "Candidate_ID": "",
    "Name": "",
    "Job_Role": "",
    "Contract_Role": "",
    "Infosys_Designation": "",
    "PU": "",
    "DU": "",
    "Project_Code": "",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "",
    "Infys_DOJ": "",
    "Remarks": ""
  },
  {
    "GroupInfo": "Chief Architect Office",
    "JD_Role": "Architect Dot NET",
    "Location": "Offshore",
    "Niche_Commodity": "Niche",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Architect",
    "Role_Technology_Mapping": "Architect Dot NET",
    "Technology_Group": "DotNET",
    "Role_Group": "Architect",
    "Relevant_Exp": ">6",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Srirengan Kumar ",
    "Raised_On_by_Client": "4-Oct-17",
    "Need_By": "1-Dec-17",
    "VAC_onboarding_Date": "6-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "23-Nov-17",
    "Interview_Date": "4-Dec-17",
    "Client_confirmation_Date": "6-Dec-17",
    "No_of_Rejections": "1",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "676317",
    "Candidate_ID": "",
    "Name": "Balaji Krishnamachary Iyengar",
    "Job_Role": "Lead Architect",
    "Contract_Role": "Lead Architect",
    "Infosys_Designation": "Senior Technology Architect",
    "PU": "FSSTAR",
    "DU": "FSSTAR-1",
    "Project_Code": "NCF101CA",
    "NCS_ID": "",
    "NCS_Email": "balaji.k.iyenga@ncs.com.sg",
    "Interview_Status": "Closed - Interview done",
    "Lateral": "NonLateral",
    "Infys_DOJ": "22-Sep-14",
    "Remarks": ""
  },
  {
    "GroupInfo": "Chief Architect Office",
    "JD_Role": "Architect Dot NET",
    "Location": "Offshore",
    "Niche_Commodity": "Niche",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Architect",
    "Role_Technology_Mapping": "Architect Dot NET",
    "Technology_Group": "DotNET",
    "Role_Group": "Architect",
    "Relevant_Exp": ">6",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Srirengan Kumar ",
    "Raised_On_by_Client": "4-Oct-17",
    "Need_By": "1-Dec-17",
    "VAC_onboarding_Date": "",
    "Onboarding_Month": "",
    "Profile_Shared_Date": "",
    "Interview_Date": "",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Open",
    "Onboarding_Status": "Open",
    "Merged_Status": "Open-Open",
    "Infosy_Emp_Id": "",
    "Candidate_ID": "",
    "Name": "",
    "Job_Role": "",
    "Contract_Role": "",
    "Infosys_Designation": "",
    "PU": "",
    "DU": "",
    "Project_Code": "",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "",
    "Infys_DOJ": "",
    "Remarks": ""
  },
  {
    "GroupInfo": "Chief Architect Office",
    "JD_Role": "Senior Java Developer",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Developer",
    "Role_Technology_Mapping": "Developer - Java",
    "Technology_Group": "Java/J2EE",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": ">2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Srirengan Kumar ",
    "Raised_On_by_Client": "4-Oct-17",
    "Need_By": "1-Dec-17",
    "VAC_onboarding_Date": "",
    "Onboarding_Month": "",
    "Profile_Shared_Date": "",
    "Interview_Date": "",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "1",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Open",
    "Onboarding_Status": "Open",
    "Merged_Status": "Open-Open",
    "Infosy_Emp_Id": "",
    "Candidate_ID": "",
    "Name": "",
    "Job_Role": "",
    "Contract_Role": "",
    "Infosys_Designation": "",
    "PU": "",
    "DU": "",
    "Project_Code": "",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "",
    "Infys_DOJ": "",
    "Remarks": ""
  },
  {
    "GroupInfo": "Chief Architect Office - Batch 2",
    "JD_Role": "DevOps Specialists",
    "Location": "Offshore",
    "Niche_Commodity": "Niche",
    "Key_Posn": "",
    "Customer_Role_Mapping": "DevOps Specialists",
    "Role_Technology_Mapping": "DevOps Specialists",
    "Technology_Group": "DevOps",
    "Role_Group": "Others",
    "Relevant_Exp": "2-5",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Srirengan Kumar ",
    "Raised_On_by_Client": "14-Feb-18",
    "Need_By": "20-Feb-18",
    "VAC_onboarding_Date": "26-Feb-18",
    "Onboarding_Month": "Feb",
    "Profile_Shared_Date": "14-Feb-18",
    "Interview_Date": "15-Feb-18",
    "Client_confirmation_Date": "20-Feb-18",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "785130",
    "Candidate_ID": "",
    "Name": "Niketa Abhirendraprasad Sinha",
    "Job_Role": "DevOps Specialists",
    "Contract_Role": "Business Analyst",
    "Infosys_Designation": "Senior Associate Consultant",
    "PU": "ECSADMC",
    "DU": "ECSADMC-DOA",
    "Project_Code": "NCO101PD",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "Closed - Interview done",
    "Lateral": "NonSingtelSlot",
    "Infys_DOJ": "5-Feb-18",
    "Remarks": ""
  },
  {
    "GroupInfo": "Chief Architect Office - Batch 2",
    "JD_Role": "DevOps Specialists",
    "Location": "Offshore",
    "Niche_Commodity": "Niche",
    "Key_Posn": "",
    "Customer_Role_Mapping": "DevOps Specialists",
    "Role_Technology_Mapping": "DevOps Specialists",
    "Technology_Group": "DevOps",
    "Role_Group": "Others",
    "Relevant_Exp": "2-5",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Srirengan Kumar ",
    "Raised_On_by_Client": "14-Feb-18",
    "Need_By": "30-Mar-18",
    "VAC_onboarding_Date": "26-Mar-18",
    "Onboarding_Month": "Mar",
    "Profile_Shared_Date": "7-Mar-18",
    "Interview_Date": "14-Mar-18",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "1",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Open",
    "Onboarding_Status": "Open",
    "Merged_Status": "Open-Open",
    "Infosy_Emp_Id": "",
    "Candidate_ID": "",
    "Name": "",
    "Job_Role": "",
    "Contract_Role": "",
    "Infosys_Designation": "",
    "PU": "",
    "DU": "",
    "Project_Code": "",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "",
    "Infys_DOJ": "",
    "Remarks": ""
  },
  {
    "GroupInfo": "DevOps (SZ)",
    "JD_Role": "Junior DevOps Specialists",
    "Location": "Offshore",
    "Niche_Commodity": "Niche",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Devops",
    "Role_Technology_Mapping": "Junior DevOps Specialists",
    "Technology_Group": "DevOps",
    "Role_Group": "Others",
    "Relevant_Exp": "#N/A",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Kuo Feng ",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "",
    "Onboarding_Month": "",
    "Profile_Shared_Date": "",
    "Interview_Date": "",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Abandoned",
    "Onboarding_Status": "Abandoned",
    "Merged_Status": "Abandoned-Abandoned",
    "Infosy_Emp_Id": "",
    "Candidate_ID": "",
    "Name": "",
    "Job_Role": "",
    "Contract_Role": "",
    "Infosys_Designation": "",
    "PU": "",
    "DU": "",
    "Project_Code": "",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "",
    "Infys_DOJ": "",
    "Remarks": "PSO Descoped"
  },
  {
    "GroupInfo": "DevOps (SZ)",
    "JD_Role": "Junior DevOps Specialists",
    "Location": "Offshore",
    "Niche_Commodity": "Niche",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Devops",
    "Role_Technology_Mapping": "Junior DevOps Specialists",
    "Technology_Group": "DevOps",
    "Role_Group": "Others",
    "Relevant_Exp": "#N/A",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Kuo Feng ",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "",
    "Onboarding_Month": "",
    "Profile_Shared_Date": "",
    "Interview_Date": "",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Abandoned",
    "Onboarding_Status": "Abandoned",
    "Merged_Status": "Abandoned-Abandoned",
    "Infosy_Emp_Id": "",
    "Candidate_ID": "",
    "Name": "",
    "Job_Role": "",
    "Contract_Role": "",
    "Infosys_Designation": "",
    "PU": "",
    "DU": "",
    "Project_Code": "",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "",
    "Infys_DOJ": "",
    "Remarks": "PSO Descoped"
  },
  {
    "GroupInfo": "DevOps (SZ)",
    "JD_Role": "Junior DevOps Specialists",
    "Location": "Offshore",
    "Niche_Commodity": "Niche",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Devops",
    "Role_Technology_Mapping": "Junior DevOps Specialists",
    "Technology_Group": "DevOps",
    "Role_Group": "Others",
    "Relevant_Exp": "#N/A",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Kuo Feng ",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "",
    "Onboarding_Month": "",
    "Profile_Shared_Date": "",
    "Interview_Date": "",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Abandoned",
    "Onboarding_Status": "Abandoned",
    "Merged_Status": "Abandoned-Abandoned",
    "Infosy_Emp_Id": "",
    "Candidate_ID": "",
    "Name": "",
    "Job_Role": "",
    "Contract_Role": "",
    "Infosys_Designation": "",
    "PU": "",
    "DU": "",
    "Project_Code": "",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "",
    "Infys_DOJ": "",
    "Remarks": "PSO Descoped"
  },
  {
    "GroupInfo": "Digital IntelliSURF",
    "JD_Role": "Technical Lead - Java",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "Y",
    "Customer_Role_Mapping": "Technical Lead",
    "Role_Technology_Mapping": "Technical Lead - Java",
    "Technology_Group": "Java/J2EE",
    "Role_Group": "TL/BSA",
    "Relevant_Exp": ">4",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Tok Wu Chuan",
    "Raised_On_by_Client": "15-Nov-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "1-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "16-Nov-17",
    "Interview_Date": "7-Nov-17",
    "Client_confirmation_Date": "11-Nov-17",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "725830",
    "Candidate_ID": "",
    "Name": "Vishwanath Narayan Chadichal",
    "Job_Role": "Technical Lead - Java",
    "Contract_Role": "Technical Lead",
    "Infosys_Designation": "Technology Lead",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCADISPZ",
    "NCS_ID": "",
    "NCS_Email": "vishwanath.chadichal@ncs.com.sg",
    "Interview_Status": "Closed - Interview done",
    "Lateral": "NonLateral",
    "Infys_DOJ": "28-Dec-15",
    "Remarks": ""
  },
  {
    "GroupInfo": "Digital IntelliSURF",
    "JD_Role": "Technical Lead - Java",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "Y",
    "Customer_Role_Mapping": "Technical Lead",
    "Role_Technology_Mapping": "Technical Lead - Java",
    "Technology_Group": "Java/J2EE",
    "Role_Group": "TL/BSA",
    "Relevant_Exp": ">4",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Tok Wu Chuan",
    "Raised_On_by_Client": "15-Nov-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "1-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "16-Nov-17",
    "Interview_Date": "14-Nov-17",
    "Client_confirmation_Date": "15-Nov-17",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "771742",
    "Candidate_ID": "",
    "Name": "Praveen Kumar Swarnakar",
    "Job_Role": "Architect",
    "Contract_Role": "Architect",
    "Infosys_Designation": "Technology Architect",
    "PU": "ECSADMCATS",
    "DU": "ECSADM-CATS",
    "Project_Code": "NCADISPZ",
    "NCS_ID": "ncspraveensw",
    "NCS_Email": "praveen.swarnakar@ncs.com.sg",
    "Interview_Status": "Closed - Interview done",
    "Lateral": "NonSingtelSlot",
    "Infys_DOJ": "25-Sep-17",
    "Remarks": ""
  },
  {
    "GroupInfo": "Digital IntelliSURF",
    "JD_Role": "Senior DBA",
    "Location": "Offshore",
    "Niche_Commodity": "Niche",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Senior DBA",
    "Role_Technology_Mapping": "Senior DBA",
    "Technology_Group": "DBA",
    "Role_Group": "Others",
    "Relevant_Exp": "> 4",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Tok Wu Chuan",
    "Raised_On_by_Client": "15-Nov-17",
    "Need_By": "15-Nov-17",
    "VAC_onboarding_Date": "16-Jan-18",
    "Onboarding_Month": "Jan",
    "Profile_Shared_Date": "10-Jan-18",
    "Interview_Date": "15-Jan-18",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "CISRUN",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "781598",
    "Candidate_ID": "",
    "Name": "Mahendrakumar Dameshwar Rahangdale",
    "Job_Role": "Junior DBA",
    "Contract_Role": "Junior DBA",
    "Infosys_Designation": "Technology Analyst",
    "PU": "CISRUN",
    "DU": "RUNECSAMR04",
    "Project_Code": "NCC04PZ3",
    "NCS_ID": "ncsmahendrak",
    "NCS_Email": "mahendra.kumar@ncs.com.sg ",
    "Interview_Status": "Closed - Interview done",
    "Lateral": "NonSingtelSlot",
    "Infys_DOJ": "1-Jan-18",
    "Remarks": ""
  },
  {
    "GroupInfo": "Digital IntelliSURF",
    "JD_Role": "UI / UX Developer",
    "Location": "Offshore",
    "Niche_Commodity": "Niche",
    "Key_Posn": "",
    "Customer_Role_Mapping": "UI / UX Developer",
    "Role_Technology_Mapping": "UI / UX Developer",
    "Technology_Group": "UI/UX",
    "Role_Group": "Others",
    "Relevant_Exp": "> 2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Tok Wu Chuan",
    "Raised_On_by_Client": "15-Nov-17",
    "Need_By": "1-Dec-17",
    "VAC_onboarding_Date": "6-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "27-Nov-17",
    "Interview_Date": "5-Dec-17",
    "Client_confirmation_Date": "6-Dec-17",
    "No_of_Rejections": "1",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "844467",
    "Candidate_ID": "",
    "Name": "Bhakti Laxman Patil",
    "Job_Role": "Developer - Java",
    "Contract_Role": "UI / UX Developer",
    "Infosys_Designation": "Technology Support Specialist",
    "PU": "BPOTSO",
    "DU": "BPOTSOINFBPO",
    "Project_Code": "NCTS01PD",
    "NCS_ID": "",
    "NCS_Email": "bhakti.patil@ncs.com.sg",
    "Interview_Status": "Closed - Interview done",
    "Lateral": "NonLateral",
    "Infys_DOJ": "4-Sep-17",
    "Remarks": ""
  },
  {
    "GroupInfo": "Digital IntelliSURF",
    "JD_Role": "Developer - Java",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Developer",
    "Role_Technology_Mapping": "Developer - Java",
    "Technology_Group": "Java/J2EE",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": ">2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Tok Wu Chuan",
    "Raised_On_by_Client": "15-Nov-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "18-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "14-Dec-17",
    "Interview_Date": "15-Jan-18",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "3",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "777716",
    "Candidate_ID": "",
    "Name": "Gaurav Sagar Ishwarkar",
    "Job_Role": "Developer - Java",
    "Contract_Role": "Developer",
    "Infosys_Designation": "Senior Systems Engineer",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCADISPZ",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "Closed - Interview done",
    "Lateral": "SingtelSlot",
    "Infys_DOJ": "4-Dec-17",
    "Remarks": ""
  },
  {
    "GroupInfo": "Digital IntelliSURF",
    "JD_Role": "Developer - Java",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Developer",
    "Role_Technology_Mapping": "Developer - Java",
    "Technology_Group": "Java/J2EE",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": ">2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Tok Wu Chuan",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "1-Dec-17",
    "VAC_onboarding_Date": "6-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "27-Nov-17",
    "Interview_Date": "5-Dec-17",
    "Client_confirmation_Date": "6-Dec-17",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "846637",
    "Candidate_ID": "",
    "Name": "Nagesh Shankar Dhanashetti",
    "Job_Role": "Developer - Java",
    "Contract_Role": "Developer",
    "Infosys_Designation": "Technology Support Specialist",
    "PU": "BPOTSO",
    "DU": "BPOTSOINFBPO",
    "Project_Code": "NCTS01PD",
    "NCS_ID": "",
    "NCS_Email": "nagesh.s.dhanashetti@ncs.com.sg",
    "Interview_Status": "Closed - Interview done",
    "Lateral": "NonLateral",
    "Infys_DOJ": "13-Nov-17",
    "Remarks": ""
  },
  {
    "GroupInfo": "Digital IntelliSURF",
    "JD_Role": "Developer - Java",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Developer",
    "Role_Technology_Mapping": "Developer - Java",
    "Technology_Group": "Java/J2EE",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": ">2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Tok Wu Chuan",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "1-Dec-17",
    "VAC_onboarding_Date": "",
    "Onboarding_Month": "",
    "Profile_Shared_Date": "",
    "Interview_Date": "",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Abandoned",
    "Onboarding_Status": "Abandoned",
    "Merged_Status": "Abandoned-Abandoned",
    "Infosy_Emp_Id": "",
    "Candidate_ID": "",
    "Name": "",
    "Job_Role": "",
    "Contract_Role": "",
    "Infosys_Designation": "",
    "PU": "",
    "DU": "",
    "Project_Code": "",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "",
    "Infys_DOJ": "",
    "Remarks": ""
  },
  {
    "GroupInfo": "Digital IntelliSURF",
    "JD_Role": "Developer - Java",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Developer",
    "Role_Technology_Mapping": "Developer - Java",
    "Technology_Group": "Java/J2EE",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": ">2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Tok Wu Chuan",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "1-Dec-17",
    "VAC_onboarding_Date": "19-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "27-Dec-17",
    "Interview_Date": "16-Jan-18",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "777734",
    "Candidate_ID": "",
    "Name": "Saurabh Yogeshwar Mahajan",
    "Job_Role": "Developer - Java",
    "Contract_Role": "Developer",
    "Infosys_Designation": "Senior Systems Engineer",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCADISPZ",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "Closed - Interview done",
    "Lateral": "SingtelSlot",
    "Infys_DOJ": "4-Dec-17",
    "Remarks": ""
  },
  {
    "GroupInfo": "Digital IntelliSURF",
    "JD_Role": "Functional Test Analyst",
    "Location": "Offshore",
    "Niche_Commodity": "Niche",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Functional Test Analyst",
    "Role_Technology_Mapping": "Functional Test Analyst",
    "Technology_Group": "Testing",
    "Role_Group": "Test Analysts/Engineers",
    "Relevant_Exp": ">2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Tok Wu Chuan",
    "Raised_On_by_Client": "15-Nov-17",
    "Need_By": "1-Dec-17",
    "VAC_onboarding_Date": "14-Feb-18",
    "Onboarding_Month": "Feb",
    "Profile_Shared_Date": "12-Dec-17",
    "Interview_Date": "16-Jan-18",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "IVS",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "782938",
    "Candidate_ID": "",
    "Name": "Anshul Nayak",
    "Job_Role": "Functional Test Lead",
    "Contract_Role": "Functional Test Lead",
    "Infosys_Designation": "Technical Test Lead",
    "PU": "IVS-SS",
    "DU": "IVSSS-MOBL2",
    "Project_Code": "NCMA01PD",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "Closed - No Interview",
    "Lateral": "NonLateral",
    "Infys_DOJ": "8-Jan-18",
    "Remarks": ""
  },
  {
    "GroupInfo": "NHG EIMR-IMAR (SZ)",
    "JD_Role": "Technical Lead - Dot NET",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "Y",
    "Customer_Role_Mapping": "Technical Lead",
    "Role_Technology_Mapping": "Technical Lead - Dot NET",
    "Technology_Group": "DotNET",
    "Role_Group": "TL/BSA",
    "Relevant_Exp": ">5",
    "Exp_on_Date_of_Onboarding": "7.6",
    "NCS_Contact": "Ichsan Zen ",
    "Raised_On_by_Client": "1-Dec-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "9-Feb-18",
    "Onboarding_Month": "Feb",
    "Profile_Shared_Date": "31-Jan-18",
    "Interview_Date": "2-Feb-18",
    "Client_confirmation_Date": "9-Feb-18",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "783768",
    "Candidate_ID": "12004726",
    "Name": "Shubhangi Rathod",
    "Job_Role": "Technical Lead - Java",
    "Contract_Role": "Technical Lead",
    "Infosys_Designation": "Technology Lead",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCA101PD",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "Closed-Interview Done",
    "Lateral": "SingtelSlot",
    "Infys_DOJ": "22-Jan-18",
    "Remarks": ""
  },
  {
    "GroupInfo": "NHG EIMR-IMAR (SZ)",
    "JD_Role": "Technical Lead - Dot NET",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "Y",
    "Customer_Role_Mapping": "Technical Lead",
    "Role_Technology_Mapping": "Technical Lead - Dot NET",
    "Technology_Group": "DotNET",
    "Role_Group": "TL/BSA",
    "Relevant_Exp": ">5",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Ichsan Zen ",
    "Raised_On_by_Client": "1-Dec-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "",
    "Onboarding_Month": "",
    "Profile_Shared_Date": "",
    "Interview_Date": "",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Abandoned",
    "Onboarding_Status": "Abandoned",
    "Merged_Status": "Abandoned-Abandoned",
    "Infosy_Emp_Id": "",
    "Candidate_ID": "",
    "Name": "",
    "Job_Role": "",
    "Contract_Role": "",
    "Infosys_Designation": "",
    "PU": "",
    "DU": "",
    "Project_Code": "",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "",
    "Infys_DOJ": "",
    "Remarks": ""
  },
  {
    "GroupInfo": "NHG EIMR-IMAR (SZ)",
    "JD_Role": "Developer - Dot NET",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Developer",
    "Role_Technology_Mapping": "Developer - Dot NET",
    "Technology_Group": "DotNET",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": ">2",
    "Exp_on_Date_of_Onboarding": "4.4",
    "NCS_Contact": "Ichsan Zen ",
    "Raised_On_by_Client": "1-Dec-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "1-Feb-18",
    "Onboarding_Month": "Feb",
    "Profile_Shared_Date": "31-Jan-18",
    "Interview_Date": "",
    "Client_confirmation_Date": "21-Feb-18",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "783344",
    "Candidate_ID": "10143541",
    "Name": "Vishal Mahajan",
    "Job_Role": "Business Analyst - Dot NET",
    "Contract_Role": "Business Analyst",
    "Infosys_Designation": "Technology Analyst",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCA101PD",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "SingtelSlot",
    "Infys_DOJ": "16-Jan-18",
    "Remarks": ""
  },
  {
    "GroupInfo": "NHG EIMR-IMAR (SZ)",
    "JD_Role": "Developer - Dot NET",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Developer",
    "Role_Technology_Mapping": "Developer - Dot NET",
    "Technology_Group": "DotNET",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": ">2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Ichsan Zen ",
    "Raised_On_by_Client": "1-Dec-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "",
    "Onboarding_Month": "",
    "Profile_Shared_Date": "",
    "Interview_Date": "",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Abandoned",
    "Onboarding_Status": "Abandoned",
    "Merged_Status": "Abandoned-Abandoned",
    "Infosy_Emp_Id": "",
    "Candidate_ID": "",
    "Name": "",
    "Job_Role": "",
    "Contract_Role": "",
    "Infosys_Designation": "",
    "PU": "",
    "DU": "",
    "Project_Code": "",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "",
    "Infys_DOJ": "",
    "Remarks": ""
  },
  {
    "GroupInfo": "NHG EIMR-IMAR (SZ)",
    "JD_Role": "Developer - Dot NET",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Developer",
    "Role_Technology_Mapping": "Developer - Dot NET",
    "Technology_Group": "DotNET",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": ">2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Ichsan Zen ",
    "Raised_On_by_Client": "1-Dec-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "",
    "Onboarding_Month": "",
    "Profile_Shared_Date": "",
    "Interview_Date": "",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Abandoned",
    "Onboarding_Status": "Abandoned",
    "Merged_Status": "Abandoned-Abandoned",
    "Infosy_Emp_Id": "",
    "Candidate_ID": "",
    "Name": "",
    "Job_Role": "",
    "Contract_Role": "",
    "Infosys_Designation": "",
    "PU": "",
    "DU": "",
    "Project_Code": "",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "",
    "Infys_DOJ": "",
    "Remarks": ""
  },
  {
    "GroupInfo": "NHG EIMR-IMAR (SZ)",
    "JD_Role": "Developer - Dot NET",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Developer",
    "Role_Technology_Mapping": "Developer - Dot NET",
    "Technology_Group": "DotNET",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": ">2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Ichsan Zen ",
    "Raised_On_by_Client": "1-Dec-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "",
    "Onboarding_Month": "",
    "Profile_Shared_Date": "",
    "Interview_Date": "",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Abandoned",
    "Onboarding_Status": "Abandoned",
    "Merged_Status": "Abandoned-Abandoned",
    "Infosy_Emp_Id": "",
    "Candidate_ID": "",
    "Name": "",
    "Job_Role": "",
    "Contract_Role": "",
    "Infosys_Designation": "",
    "PU": "",
    "DU": "",
    "Project_Code": "",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "",
    "Infys_DOJ": "",
    "Remarks": ""
  },
  {
    "GroupInfo": "NHG EIMR-IMAR (SZ)",
    "JD_Role": "Junior Developer - Dot NET",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Junior Developer",
    "Role_Technology_Mapping": "Junior Developer - Dot NET",
    "Technology_Group": "DotNET",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": "1--2",
    "Exp_on_Date_of_Onboarding": "1.3",
    "NCS_Contact": "Ichsan Zen ",
    "Raised_On_by_Client": "1-Dec-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "6-Feb-18",
    "Onboarding_Month": "Feb",
    "Profile_Shared_Date": "19-Feb-18",
    "Interview_Date": "",
    "Client_confirmation_Date": "21-Feb-18",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "258812",
    "Candidate_ID": "",
    "Name": "Shakuntala Arunkumar Loni",
    "Job_Role": "Junior Developer - Dot NET",
    "Contract_Role": "Junior Developer",
    "Infosys_Designation": "Systems Engineer",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCASUCON",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "Subcon",
    "Infys_DOJ": "6-Feb-18",
    "Remarks": ""
  },
  {
    "GroupInfo": "NHG EIMR-IMAR (SZ)",
    "JD_Role": "Junior Developer - Dot NET",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Junior Developer",
    "Role_Technology_Mapping": "Junior Developer - Dot NET",
    "Technology_Group": "DotNET",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": "1--2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Ichsan Zen ",
    "Raised_On_by_Client": "1-Dec-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "",
    "Onboarding_Month": "",
    "Profile_Shared_Date": "",
    "Interview_Date": "",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Abandoned",
    "Onboarding_Status": "Abandoned",
    "Merged_Status": "Abandoned-Abandoned",
    "Infosy_Emp_Id": "",
    "Candidate_ID": "",
    "Name": "",
    "Job_Role": "",
    "Contract_Role": "",
    "Infosys_Designation": "",
    "PU": "",
    "DU": "",
    "Project_Code": "",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "",
    "Infys_DOJ": "",
    "Remarks": ""
  },
  {
    "GroupInfo": "NHG E-PRESCRIPTION (SZ)",
    "JD_Role": "Technical Lead - Dot NET",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "Y",
    "Customer_Role_Mapping": "Technical Lead",
    "Role_Technology_Mapping": "Technical Lead - Dot NET",
    "Technology_Group": "DotNET",
    "Role_Group": "TL/BSA",
    "Relevant_Exp": ">5",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Lee Ming ",
    "Raised_On_by_Client": "1-Dec-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "1-Mar-18",
    "Onboarding_Month": "Mar",
    "Profile_Shared_Date": "20-Feb-18",
    "Interview_Date": "27-Feb-18",
    "Client_confirmation_Date": "28-Feb-18",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "786473",
    "Candidate_ID": "58665617",
    "Name": "Vaibhav Pandey",
    "Job_Role": "Technical Lead - Dot NET",
    "Contract_Role": "Technical Lead",
    "Infosys_Designation": "Technology Lead",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCA101PD",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "SingtelSlot",
    "Infys_DOJ": "12-Feb-18",
    "Remarks": ""
  },
  {
    "GroupInfo": "NHG E-PRESCRIPTION (SZ)",
    "JD_Role": "Developer - Dot NET",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Developer",
    "Role_Technology_Mapping": "Developer - Dot NET",
    "Technology_Group": "DotNET",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": ">2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Lee Ming ",
    "Raised_On_by_Client": "1-Dec-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "15-Feb-18",
    "Onboarding_Month": "Feb",
    "Profile_Shared_Date": "20-Feb-18",
    "Interview_Date": "",
    "Client_confirmation_Date": "28-Feb-18",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "785314",
    "Candidate_ID": "62998835",
    "Name": "Kishan Vankatrao Gangapure",
    "Job_Role": "Developer - Dot NET",
    "Contract_Role": "Developer",
    "Infosys_Designation": "Senior Systems Engineer",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCA101PD",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "SingtelSlot",
    "Infys_DOJ": "5-Feb-18",
    "Remarks": ""
  },
  {
    "GroupInfo": "NHG E-PRESCRIPTION (SZ)",
    "JD_Role": "Developer - Dot NET",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Developer",
    "Role_Technology_Mapping": "Developer - Dot NET",
    "Technology_Group": "DotNET",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": ">2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Lee Ming ",
    "Raised_On_by_Client": "1-Dec-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "26-Feb-18",
    "Onboarding_Month": "Feb",
    "Profile_Shared_Date": "20-Feb-18",
    "Interview_Date": "",
    "Client_confirmation_Date": "28-Feb-18",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "786351",
    "Candidate_ID": "12003673",
    "Name": "Divya Chhabda",
    "Job_Role": "Junior Developer - Dot Net",
    "Contract_Role": "Junior Developer",
    "Infosys_Designation": "Senior Systems Engineer",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCA101PD",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "SingtelSlot",
    "Infys_DOJ": "12-Feb-18",
    "Remarks": ""
  },
  {
    "GroupInfo": "HPB CAMS2 (SZ)",
    "JD_Role": "Java Project Manager",
    "Location": "Offshore",
    "Niche_Commodity": "Niche",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Project Manager",
    "Role_Technology_Mapping": "Project Manager",
    "Technology_Group": "Project Mgr",
    "Role_Group": "TM/PM/SM",
    "Relevant_Exp": ">6",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Fan Zhaowei ",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "31-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "30-Nov-17",
    "Interview_Date": "30-Nov-17",
    "Client_confirmation_Date": "30-Nov-17",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "604953",
    "Candidate_ID": "",
    "Name": "Pravin Sandipan Mane",
    "Job_Role": "Project Manager",
    "Contract_Role": "Project Manager",
    "Infosys_Designation": "Project Manager",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCAHPBPZ",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "Closed - No Interview",
    "Lateral": "NonLateral",
    "Infys_DOJ": "2-Jan-12",
    "Remarks": ""
  },
  {
    "GroupInfo": "HPB CAMS2 (SZ)",
    "JD_Role": "Junior Developer - Java",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Junior Developer",
    "Role_Technology_Mapping": "Junior Developer - Java",
    "Technology_Group": "Java/J2EE",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": "1--2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Fan Zhaowei ",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "14-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "11-Dec-17",
    "Interview_Date": "13-Dec-17",
    "Client_confirmation_Date": "13-Dec-17",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "768282",
    "Candidate_ID": "",
    "Name": "Mohit Rawat",
    "Job_Role": "Junior Developer - Dot NET",
    "Contract_Role": "Junior Developer",
    "Infosys_Designation": "Systems Engineer",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCAHPBPZ",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "Closed - Interview done",
    "Lateral": "NonLateral",
    "Infys_DOJ": "21-Aug-17",
    "Remarks": ""
  },
  {
    "GroupInfo": "HPB CAMS2 (SZ)",
    "JD_Role": "Junior Developer - Java",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Junior Developer",
    "Role_Technology_Mapping": "Junior Developer - Java",
    "Technology_Group": "Java/J2EE",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": "1--2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Fan Zhaowei ",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "14-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "11-Dec-17",
    "Interview_Date": "13-Dec-17",
    "Client_confirmation_Date": "13-Dec-17",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "768359",
    "Candidate_ID": "",
    "Name": "Megha Dixit",
    "Job_Role": "Junior Developer - Dot NET",
    "Contract_Role": "Junior Developer",
    "Infosys_Designation": "Systems Engineer",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCAHPBPZ",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "Closed - Interview done",
    "Lateral": "NonLateral",
    "Infys_DOJ": "21-Aug-17",
    "Remarks": ""
  },
  {
    "GroupInfo": "HPB CAMS2 (SZ)",
    "JD_Role": "Technical Lead - Dot NET",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "Y",
    "Customer_Role_Mapping": "Technical Lead",
    "Role_Technology_Mapping": "Technical Lead - Dot NET",
    "Technology_Group": "DotNET",
    "Role_Group": "TL/BSA",
    "Relevant_Exp": ">4",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Fan Zhaowei ",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "15-Nov-17",
    "VAC_onboarding_Date": "8-Jan-18",
    "Onboarding_Month": "Jan",
    "Profile_Shared_Date": "2-Jan-18",
    "Interview_Date": "4-Jan-18",
    "Client_confirmation_Date": "4-Jan-18",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "655456",
    "Candidate_ID": "",
    "Name": "Rahul Jain",
    "Job_Role": "Technical Lead - Dot NET",
    "Contract_Role": "Business Analyst",
    "Infosys_Designation": "Technology Analyst",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCAHPBPZ",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "SingtelSlot",
    "Infys_DOJ": "10-Feb-14",
    "Remarks": ""
  },
  {
    "GroupInfo": "HPB CAMS2 (SZ)",
    "JD_Role": "Developer - Dot NET",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Developer",
    "Role_Technology_Mapping": "Developer - Dot NET",
    "Technology_Group": "DotNET",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": ">2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Fan Zhaowei ",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "18-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "14-Dec-17",
    "Interview_Date": "27-Dec-17",
    "Client_confirmation_Date": "28-Dec-17",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "751605",
    "Candidate_ID": "",
    "Name": "Amruta Chandrakant Patil",
    "Job_Role": "Developer - Dot NET",
    "Contract_Role": "Developer",
    "Infosys_Designation": "Senior Systems Engineer",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCAHPBPZ",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "NonLateral",
    "Infys_DOJ": "19-Dec-16",
    "Remarks": ""
  },
  {
    "GroupInfo": "HPB CAMS2 (SZ)",
    "JD_Role": "Developer - Dot NET",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Developer",
    "Role_Technology_Mapping": "Developer - Dot NET",
    "Technology_Group": "DotNET",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": ">2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Fan Zhaowei ",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "18-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "14-Dec-17",
    "Interview_Date": "27-Dec-17",
    "Client_confirmation_Date": "28-Dec-17",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "777598",
    "Candidate_ID": "",
    "Name": "Nikhil Narhari Barapatre",
    "Job_Role": "Developer - Dot NET",
    "Contract_Role": "Developer",
    "Infosys_Designation": "Technology Analyst",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCAHPBPZ",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "NonSingtelSlot",
    "Infys_DOJ": "4-Dec-17",
    "Remarks": ""
  },
  {
    "GroupInfo": "HPB CAMS2 (SZ)",
    "JD_Role": "Junior Developer - Dot NET",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Junior Developer",
    "Role_Technology_Mapping": "Junior Developer - Dot NET",
    "Technology_Group": "DotNET",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": "1--2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Fan Zhaowei ",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "18-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "14-Dec-17",
    "Interview_Date": "27-Dec-17",
    "Client_confirmation_Date": "28-Dec-17",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "758505",
    "Candidate_ID": "",
    "Name": "Shivani Kavish Shah",
    "Job_Role": "Junior Developer - Dot NET",
    "Contract_Role": "Junior Developer",
    "Infosys_Designation": "Systems Engineer",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCAHPBPZ",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "NonLateral",
    "Infys_DOJ": "27-Mar-17",
    "Remarks": ""
  },
  {
    "GroupInfo": "HPB CAMS2 (SZ)",
    "JD_Role": "Technical Lead - Java",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "Y",
    "Customer_Role_Mapping": "Technical Lead",
    "Role_Technology_Mapping": "Technical Lead - Java",
    "Technology_Group": "Java/J2EE",
    "Role_Group": "TL/BSA",
    "Relevant_Exp": ">5",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Fan Zhaowei ",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "6-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "4-Dec-17",
    "Interview_Date": "6-Dec-17",
    "Client_confirmation_Date": "6-Dec-17",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "180066",
    "Candidate_ID": "",
    "Name": "Manoj Kumar Shishupal rao Cheulwar",
    "Job_Role": "Technical Lead - Java",
    "Contract_Role": "Technical Lead",
    "Infosys_Designation": "Technology Lead",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCAHPBPZ",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "NonLateral",
    "Infys_DOJ": "9-May-11",
    "Remarks": ""
  },
  {
    "GroupInfo": "HPB CAMS2 (SZ)",
    "JD_Role": "Technical Lead - Java",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "Y",
    "Customer_Role_Mapping": "Technical Lead",
    "Role_Technology_Mapping": "Technical Lead - Java",
    "Technology_Group": "Java/J2EE",
    "Role_Group": "TL/BSA",
    "Relevant_Exp": ">5",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Fan Zhaowei ",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "1-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "21-Dec-17",
    "Interview_Date": "8-Nov-17",
    "Client_confirmation_Date": "11-Nov-17",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "770597",
    "Candidate_ID": "",
    "Name": "Shubhangi BalaBhau Deshmukh",
    "Job_Role": "Technical Lead - Java",
    "Contract_Role": "Technical Lead",
    "Infosys_Designation": "Technology Lead",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCAHPBPZ",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "NonSingtelSlot",
    "Infys_DOJ": "11-Sep-17",
    "Remarks": ""
  },
  {
    "GroupInfo": "HPB CAMS2 (SZ)",
    "JD_Role": "Technical Lead - Java",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "Y",
    "Customer_Role_Mapping": "Technical Lead",
    "Role_Technology_Mapping": "Technical Lead - Java",
    "Technology_Group": "Java/J2EE",
    "Role_Group": "TL/BSA",
    "Relevant_Exp": ">5",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Fan Zhaowei ",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "8-Jan-18",
    "Onboarding_Month": "Jan",
    "Profile_Shared_Date": "4-Jan-18",
    "Interview_Date": "5-Jan-18",
    "Client_confirmation_Date": "5-Jan-18",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "757831",
    "Candidate_ID": "",
    "Name": "Ashwini Ramesh Shikhare",
    "Job_Role": "Technical Lead - Java",
    "Contract_Role": "Technical Lead",
    "Infosys_Designation": "Technology Lead",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCAHPBPZ",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "SingtelSlot",
    "Infys_DOJ": "20-Mar-17",
    "Remarks": ""
  },
  {
    "GroupInfo": "HPB CAMS2 (SZ)",
    "JD_Role": "Senior Java Developer",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Developer",
    "Role_Technology_Mapping": "Developer - Java",
    "Technology_Group": "Java/J2EE",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": ">2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Fan Zhaowei ",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "1-Dec-17",
    "VAC_onboarding_Date": "14-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "11-Dec-17",
    "Interview_Date": "11-Dec-17",
    "Client_confirmation_Date": "13-Dec-17",
    "No_of_Rejections": "1",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "741147",
    "Candidate_ID": "",
    "Name": "Pallavi Baban Dumbre",
    "Job_Role": "Developer - Java",
    "Contract_Role": "Developer",
    "Infosys_Designation": "Senior Systems Engineer",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCAHPBPZ",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "Closed - Interview done",
    "Lateral": "NonLateral",
    "Infys_DOJ": "11-Jul-16",
    "Remarks": ""
  },
  {
    "GroupInfo": "HPB CAMS2 (SZ)",
    "JD_Role": "Senior Java Developer",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Developer",
    "Role_Technology_Mapping": "Developer - Java",
    "Technology_Group": "Java/J2EE",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": ">2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Fan Zhaowei ",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "15-Nov-17",
    "VAC_onboarding_Date": "6-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "4-Dec-17",
    "Interview_Date": "13-Nov-17",
    "Client_confirmation_Date": "16-Nov-17",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "773610",
    "Candidate_ID": "",
    "Name": "Shweta Bhalchandra Prabhu",
    "Job_Role": "Developer - Java",
    "Contract_Role": "Developer",
    "Infosys_Designation": "Technology Analyst",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCAHPBPZ",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "NonSingtelSlot",
    "Infys_DOJ": "16-Oct-17",
    "Remarks": ""
  },
  {
    "GroupInfo": "HPB CAMS2 (SZ)",
    "JD_Role": "Senior Java Developer",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Developer",
    "Role_Technology_Mapping": "Developer - Java",
    "Technology_Group": "Java/J2EE",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": ">2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Fan Zhaowei ",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "14-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "11-Dec-17",
    "Interview_Date": "13-Dec-17",
    "Client_confirmation_Date": "13-Dec-17",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "777735",
    "Candidate_ID": "",
    "Name": "Vikrant V Upase",
    "Job_Role": "Developer - Java",
    "Contract_Role": "Developer",
    "Infosys_Designation": "Technology Analyst",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCAHPBPZ",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "Closed - No Interview",
    "Lateral": "SingtelSlot",
    "Infys_DOJ": "4-Dec-17",
    "Remarks": ""
  },
  {
    "GroupInfo": "HPB CAMS2 (SZ)",
    "JD_Role": "Senior Java Developer",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Developer",
    "Role_Technology_Mapping": "Developer - Java",
    "Technology_Group": "Java/J2EE",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": ">2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Fan Zhaowei ",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "22-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "15-Dec-17",
    "Interview_Date": "27-Dec-17",
    "Client_confirmation_Date": "28-Dec-17",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "774989",
    "Candidate_ID": "",
    "Name": "Aman Vij",
    "Job_Role": "Developer - Java",
    "Contract_Role": "Developer",
    "Infosys_Designation": "Senior Systems Engineer",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCAHPBPZ",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "Closed - No Interview",
    "Lateral": "NonSingtelSlot",
    "Infys_DOJ": "6-Nov-17",
    "Remarks": ""
  },
  {
    "GroupInfo": "HPB CAMS2 (SZ)",
    "JD_Role": "Technical BSA - Dot NET",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Business Analyst",
    "Role_Technology_Mapping": "Business Analyst - Java",
    "Technology_Group": "Java/J2EE",
    "Role_Group": "TL/BSA",
    "Relevant_Exp": "",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Fan Zhaowei ",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "21-Mar-18",
    "Onboarding_Month": "Mar",
    "Profile_Shared_Date": "16-Mar-18",
    "Interview_Date": "16-Mar-18",
    "Client_confirmation_Date": "19-Mar-18",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "260005",
    "Candidate_ID": "",
    "Name": "Binod Bihari Biswal",
    "Job_Role": "Technical Lead - Dot Net",
    "Contract_Role": "Technical Lead",
    "Infosys_Designation": "Technology Lead",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCASUCON",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "Closed - Interview done",
    "Lateral": "Subcon",
    "Infys_DOJ": "21-Mar-18",
    "Remarks": ""
  },
  {
    "GroupInfo": "HPB CAMS2 (SZ)",
    "JD_Role": "Senior Java Developer",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Developer",
    "Role_Technology_Mapping": "Developer - Java",
    "Technology_Group": "Java/J2EE",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": ">2",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "Fan Zhaowei ",
    "Raised_On_by_Client": "27-Nov-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "19-Dec-17",
    "Onboarding_Month": "Dec",
    "Profile_Shared_Date": "15-Dec-17",
    "Interview_Date": "",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "777846",
    "Candidate_ID": "",
    "Name": "Keyur Rashikbhai Khachariya",
    "Job_Role": "Developer - Java",
    "Contract_Role": "Developer",
    "Infosys_Designation": "Senior Systems Engineer",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCAHPBPZ",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "Closed - No Interview",
    "Lateral": "SingtelSlot",
    "Infys_DOJ": "4-Dec-17",
    "Remarks": ""
  },
  {
    "GroupInfo": "MOH AMS (SZ)",
    "JD_Role": "Technical Lead - Dot NET",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "Y",
    "Customer_Role_Mapping": "Technical Lead",
    "Role_Technology_Mapping": "Technical Lead - Dot NET",
    "Technology_Group": "DotNET",
    "Role_Group": "TL/BSA",
    "Relevant_Exp": ">5",
    "Exp_on_Date_of_Onboarding": "4.2",
    "NCS_Contact": "Hong Hui ",
    "Raised_On_by_Client": "1-Dec-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "18-Jan-18",
    "Onboarding_Month": "Jan",
    "Profile_Shared_Date": "19-Feb-18",
    "Interview_Date": "27-Feb-18",
    "Client_confirmation_Date": "27-Feb-18",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "770708",
    "Candidate_ID": "",
    "Name": "Vina Pawar",
    "Job_Role": "Business Analyst - Dot NET",
    "Contract_Role": "Business Analyst",
    "Infosys_Designation": "Technology Analyst",
    "PU": "ECSADMC",
    "DU": "ECSADMC-NCS",
    "Project_Code": "NCA101PD",
    "NCS_ID": "ncsvinap",
    "NCS_Email": "vina.pawar@ncs.com.sg",
    "Interview_Status": "",
    "Lateral": "SingtelSlot",
    "Infys_DOJ": "11-Sep-17",
    "Remarks": ""
  },
  {
    "GroupInfo": "MOH AMS (SZ)",
    "JD_Role": "Developer - Dot NET",
    "Location": "Offshore",
    "Niche_Commodity": "Commodity",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Developer",
    "Role_Technology_Mapping": "Developer - Dot NET",
    "Technology_Group": "DotNET",
    "Role_Group": "Jr./Sr. Developer",
    "Relevant_Exp": "1--2",
    "Exp_on_Date_of_Onboarding": "2.2",
    "NCS_Contact": "Hong Hui ",
    "Raised_On_by_Client": "1-Dec-17",
    "Need_By": "31-Dec-17",
    "VAC_onboarding_Date": "9-Mar-18",
    "Onboarding_Month": "Mar",
    "Profile_Shared_Date": "28-Feb-18",
    "Interview_Date": "5-Mar-18",
    "Client_confirmation_Date": "6-Mar-18",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "ADM",
    "PSO_Status": "Closed",
    "Onboarding_Status": "Onboarded",
    "Merged_Status": "Onboarded-Closed",
    "Infosy_Emp_Id": "849164",
    "Candidate_ID": "849164",
    "Name": "Anil Dashrath Mane",
    "Job_Role": "Developer - Dot NET",
    "Contract_Role": "Developer",
    "Infosys_Designation": "Technology Support Specialist",
    "PU": "BPOTSO",
    "DU": "BPOTSOINFBPO",
    "Project_Code": "NCPA01AL",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "SingtelSlot",
    "Infys_DOJ": "26-Feb-18",
    "Remarks": ""
  },
  {
    "GroupInfo": "Pega ",
    "JD_Role": "Pega Project Manager",
    "Location": "Offshore",
    "Niche_Commodity": "Niche",
    "Key_Posn": "",
    "Customer_Role_Mapping": "Project Manager",
    "Role_Technology_Mapping": "Pega Project Manager",
    "Technology_Group": "Pega",
    "Role_Group": "TM/PM/SM",
    "Relevant_Exp": ">6",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "",
    "Raised_On_by_Client": "10-Jan-18",
    "Need_By": "1-Jun-18",
    "VAC_onboarding_Date": "",
    "Onboarding_Month": "",
    "Profile_Shared_Date": "",
    "Interview_Date": "",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "EAI",
    "PSO_Status": "Deferred",
    "Onboarding_Status": "",
    "Merged_Status": "-Deferred",
    "Infosy_Emp_Id": "",
    "Candidate_ID": "",
    "Name": "",
    "Job_Role": "",
    "Contract_Role": "",
    "Infosys_Designation": "",
    "PU": "",
    "DU": "",
    "Project_Code": "",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "",
    "Infys_DOJ": "",
    "Remarks": ""
  },
  {
    "GroupInfo": "Pega ",
    "JD_Role": "Pega BA/Senior Developer",
    "Location": "Offshore",
    "Niche_Commodity": "Niche",
    "Key_Posn": "",
    "Customer_Role_Mapping": "ERP Lead",
    "Role_Technology_Mapping": "Pega Senior Developer",
    "Technology_Group": "Pega",
    "Role_Group": "Others",
    "Relevant_Exp": ">7",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "",
    "Raised_On_by_Client": "10-Jan-18",
    "Need_By": "1-Jun-18",
    "VAC_onboarding_Date": "",
    "Onboarding_Month": "",
    "Profile_Shared_Date": "",
    "Interview_Date": "",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "EAI",
    "PSO_Status": "Deferred",
    "Onboarding_Status": "",
    "Merged_Status": "-Deferred",
    "Infosy_Emp_Id": "",
    "Candidate_ID": "",
    "Name": "",
    "Job_Role": "",
    "Contract_Role": "",
    "Infosys_Designation": "",
    "PU": "",
    "DU": "",
    "Project_Code": "",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "",
    "Infys_DOJ": "",
    "Remarks": ""
  },
  {
    "GroupInfo": "Pega ",
    "JD_Role": "Pega BA/Senior Developer",
    "Location": "Offshore",
    "Niche_Commodity": "Niche",
    "Key_Posn": "",
    "Customer_Role_Mapping": "ERP Lead",
    "Role_Technology_Mapping": "Pega Senior Developer",
    "Technology_Group": "Pega",
    "Role_Group": "Others",
    "Relevant_Exp": ">7",
    "Exp_on_Date_of_Onboarding": "",
    "NCS_Contact": "",
    "Raised_On_by_Client": "10-Jan-18",
    "Need_By": "1-Jun-18",
    "VAC_onboarding_Date": "",
    "Onboarding_Month": "",
    "Profile_Shared_Date": "",
    "Interview_Date": "",
    "Client_confirmation_Date": "",
    "No_of_Rejections": "0",
    "VAC_Offboarding_Date": "31-Dec-18",
    "Infosys_Unit_Owner": "EAI",
    "PSO_Status": "Deferred",
    "Onboarding_Status": "",
    "Merged_Status": "-Deferred",
    "Infosy_Emp_Id": "",
    "Candidate_ID": "",
    "Name": "",
    "Job_Role": "",
    "Contract_Role": "",
    "Infosys_Designation": "",
    "PU": "",
    "DU": "",
    "Project_Code": "",
    "NCS_ID": "",
    "NCS_Email": "",
    "Interview_Status": "",
    "Lateral": "",
    "Infys_DOJ": "",
    "Remarks": ""
  }];
  ngOnInit() {
  //  console.log(this.demandtrackernew);
  //this.onBoard.getData()
 }
}
